dist: trusty
language: node_js
node_js:
  - "7"
before_install:
  - nvm install 8.10.0 && nvm use 8.10.0
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
# install: 
#   - npm install
# test: 
#   - npm test
env:
  - LAIKA_OPTIONS="-t 5000"
after_success:
  - eval $(aws ecr get-login --region us-east-1)