dist: trusty
sudo: true
language: node_js
node_js:
  - "7"
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
before_install:
  - nvm install 8.10.0 && nvm use 8.10.0
  - pip3 install awscli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin
install: travis_wait 30 npm run start-local
install: 
  - npm install
test: 
  - npm test
  - npm run integration-test
script:
  - eval $(aws ecr get-login --region us-east-1)
  - npm run deploy-code 