dist: trusty
sudo: true
language: node_js
node_js:
  - "7"
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
before_install:
  - nvm install 8.10.0 && nvm use 8.10.0
  - pip install --upgrade --user awscli
  - pip install --upgrade --user aws-sam-cli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region us-west-2)
install: travis_wait 30 npm run start-local
install: 
  - npm install
script: 
  - npm test
  - npm run integration-test
script:
  - npm run deploy-code 