version = 0.1
[default.deploy.parameters]
stack_name = "server-side-slinger"
resolve_s3 = true
s3_prefix = "server-side-slinger"
region = "us-east-1"
profile = "server-side-slinger"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
