AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-app

    Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3
        Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
            Variables:
                TABLE_NAME: !Ref WidgetCache
        CodeUri: chrome-test/
        Runtime: nodejs8.10
        MemorySize: 1600
        Timeout: 30

Resources:
    Lifestyle:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            Handler: dashboards/Lifestyle.lambdaHandler
            CodeUri: chrome-test/
            Policies:
            - DynamoDBCrudPolicy:
                  TableName: !Ref WidgetCache
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    TABLE_NAME: !Ref WidgetCache
            Events:
                BasicCase:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /lifestyle
                        Method: get

    PressRoom:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            Handler: widgets/PressRoom.lambdaHandler
            CodeUri: chrome-test/
            Policies:
            - DynamoDBCrudPolicy:
                  TableName: !Ref WidgetCache
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    TABLE_NAME: !Ref WidgetCache
            Events:
                BasicCase:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /pressRoom
                        Method: get

    3BridgesYoga:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            Handler: widgets/3BridgesYoga.lambdaHandler
            CodeUri: chrome-test/
            Policies:
            - DynamoDBCrudPolicy:
                  TableName: !Ref WidgetCache
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    TABLE_NAME: !Ref WidgetCache
            Events:
                BasicCase:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /3by
                        Method: get

    Blaze:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            Handler: widgets/BlazeYoga.lambdaHandler
            CodeUri: chrome-test/
            Policies:
            - DynamoDBCrudPolicy:
                  TableName: !Ref WidgetCache
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    TABLE_NAME: !Ref WidgetCache
            Events:
                BasicCase:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /blaze
                        Method: get


    WidgetCache:
        Type: AWS::Serverless::SimpleTable
        Properties:
            TableName: widget-cache


#            Layers:
#                - !Ref scrapingLayer

#                PrimaryKey:
#                    Name: id
#                    Type: String
#                ProvisionedThroughput:
#                    ReadCapacityUnits: 5
#                    WriteCapacityUnits: 5
##                Tags:
##                    Department: Engineering
##                    AppType: Serverless
#                SSESpecification:
#                    SSEEnabled: true

#    scrapingLayer:
#        Type: AWS::Serverless::LayerVersion
#        Properties:
#            LayerName: ScrapingLayer
#            Description: Layer to utilize chrome scraping
#            ContentUri: scraping-layer
#            CompatibleRuntimes:
#                - nodejs8.10
#            LicenseInfo: 'Available under the MIT-0 license.'
#            RetentionPolicy: Retain

#Outputs:
#
#    HelloWorldApi:
#          Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#          Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#
#    HelloWorldFunction:
#          Description: "Hello World Lambda Function ARN"
#          Value: !GetAtt HelloWorldFunction.Arn
#
#    HelloWorldFunctionIamRole:
#          Description: "Implicit IAM Role created for Hello World function"
#          Value: !GetAtt HelloWorldFunctionRole.Arn
